# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/vivado_prj/i2c_scanner_v2/i2c_scanner_v2.srcs/sources_1/bd/i2c_scan_v2/ip/i2c_scan_v2_lmb_bram_0/i2c_scan_v2_lmb_bram_0.xci
# IP: The module: 'i2c_scan_v2_lmb_bram_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/vivado_prj/i2c_scanner_v2/i2c_scanner_v2.gen/sources_1/bd/i2c_scan_v2/ip/i2c_scan_v2_lmb_bram_0/i2c_scan_v2_lmb_bram_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'i2c_scan_v2_lmb_bram_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: e:/vivado_prj/i2c_scanner_v2/i2c_scanner_v2.srcs/sources_1/bd/i2c_scan_v2/ip/i2c_scan_v2_lmb_bram_0/i2c_scan_v2_lmb_bram_0.xci
# IP: The module: 'i2c_scan_v2_lmb_bram_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/vivado_prj/i2c_scanner_v2/i2c_scanner_v2.gen/sources_1/bd/i2c_scan_v2/ip/i2c_scan_v2_lmb_bram_0/i2c_scan_v2_lmb_bram_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'i2c_scan_v2_lmb_bram_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
